module.exports = {
  mode: 'jit',
  content: ['./src/**/*.{html,js}'],
  safelist: [
    'overflow-auto',
    'flex-col',
    'flex-auto',
    'justify-center',
    'items-center',
    'border',
    'border-y',
    'border-0',
    'border-b-0',
    'border-r-0',
    'border-x-0',
    'border-white',
    'rounded',
    'rounded-full',
    'm-2',
    'my-1',
    'my-2',
    'mb-0',
    '-mx-px',
    'pb-2',
    'pt-3',
    'pr-3',
    'h-4',
    'h-5',
    'h-6',
    'h-8',
    'w-4',
    'w-5',
    'w-6',
    'w-8',
    'w-20',
    'w-24',
    'w-28',
    'w-36',
    'w-40',
    'w-96',
    'w-full',
    'gap-2',
    'text-gray-500',
    'text-gray-300',
    'border-gray-900',
    'border-gray-800',
    'border-gray-700',
    'border-gray-600',
    'border-gray-500',
    'border-gray-400',
    'border-gray-300',
    'border-gray-200',
    'border-gray-100',
    'border-gray-50',
    'border-green-900',
    'border-green-800',
    'border-green-700',
    'border-green-600',
    'border-green-500',
    'border-green-400',
    'border-green-300',
    'border-green-200',
    'border-green-100',
    'border-green-50',
    'border-violet-900',
    'border-violet-800',
    'border-violet-700',
    'border-violet-600',
    'border-violet-500',
    'border-violet-400',
    'border-violet-300',
    'border-violet-200',
    'border-violet-100',
    'border-violet-50',
    'relative',
    'text-white',
    'bg-white'
  ],
  theme: {
    extend: {
      fontSize: {
        'xxs'  : '0.55rem',
      },
    },
  },
  plugins: [],
}
